#version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis  # Redis 호스트 이름
      SPRING_REDIS_PORT: 6379   # Redis 포트 번호

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

